export const AuthErrors = {
  ACCOUNT_NOT_FOUND: 'AUTH_ACCOUNT_NOT_FOUND',
  PROFILE_SYNC_FAILED: 'AUTH_PROFILE_SYNC_FAILED',
  INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCESS_DENIED: 'AUTH_ACCESS_DENIED',
  DUPLICATE_EMAIL: 'AUTH_DUPLICATE_EMAIL',
  DUPLICATE_USERNAME: 'AUTH_DUPLICATE_USERNAME',
} as const;
