export const StudentErrors = {
  DUPLICATE_EMAIL: 'STUDENT_DUPLICATE_EMAIL',
  DUPLICATE_REGISTRATION: 'STUDENT_DUPLICATE_REGISTRATION',
  REGISTRATION_IMMUTABLE: 'STUDENT_REGISTRATION_IMMUTABLE',
  ACCESS_DENIED: 'STUDENT_ACCESS_DENIED',
} as const;
