export const GroupErrors = {
  STUDENT_ALREADY_IN_GROUP: 'GROUP_STUDENT_ALREADY_IN_GROUP',
  ONE_LEADER_REQUIRED: 'GROUP_ONE_LEADER_REQUIRED',
  LEADER_ALREADY_EXISTS: 'GROUP_LEADER_ALREADY_EXISTS',
  PROJECT_ALREADY_ASSIGNED: 'GROUP_PROJECT_ALREADY_ASSIGNED',
  GROUP_ALREADY_HAS_PROJECT: 'GROUP_ALREADY_HAS_PROJECT',
  ACCESS_DENIED: 'GROUP_ACCESS_DENIED',
  INVALID_STATUS: 'GROUP_INVALID_STUDENT_STATUS',
  NO_PROJECT_ASSIGNED: 'GROUP_NO_PROJECT_ASSIGNED',
  ADVISOR_ALREADY_ASSIGNED: 'GROUP_ADVISOR_ALREADY_ASSIGNED',
} as const;
